# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 18:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Lease Block Geometry')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningUnitSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('palnningunit_ids', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry_actual', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Planning Unit Selection Geometry')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_planningunitselection_related', to='contenttypes.ContentType')),
                ('sharing_groups', models.ManyToManyField(blank=True, editable=False, related_name='scenarios_planningunitselection_related', to='auth.Group', verbose_name='Share with the following groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_planningunitselection_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LeaseBlock',
        ),
        migrations.RemoveField(
            model_name='leaseblockselection',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='leaseblockselection',
            name='sharing_groups',
        ),
        migrations.RemoveField(
            model_name='leaseblockselection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_avg_wind_speed',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_distance_to_awc',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_distance_to_shipping',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_distance_to_substation',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_filter_ais_density',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_filter_distance_to_shipping',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_filter_uxo',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_max_depth',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_max_distance_to_shore',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_min_depth',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_min_distance_to_shore',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_parameter_depth',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_parameter_distance_to_awc',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_parameter_distance_to_shore',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_parameter_distance_to_substation',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_parameter_sediment',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_parameter_substrate',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_parameter_wea',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_parameter_wind_speed',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_sediment',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_substrate',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='input_wea',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='lease_blocks',
        ),
        migrations.AddField(
            model_name='scenario',
            name='planning_units',
            field=models.TextField(blank=True, null=True, verbose_name='Planning Unit IDs'),
        ),
        migrations.DeleteModel(
            name='LeaseBlockSelection',
        ),
        migrations.DeleteModel(
            name='Objective',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='Sediment',
        ),
        migrations.DeleteModel(
            name='Substrate',
        ),
        migrations.DeleteModel(
            name='WEA',
        ),
    ]
