# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 01:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_auto_20171207_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningunit',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Planning Unit Geometry'),
        ),
    ]
