# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_auto_20171207_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoScenario',
            fields=[
                ('scenario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scenarios.Scenario')),
                ('input_parameter_area', models.BooleanField(default=False, verbose_name='Planning Unit Area in sq. meters')),
                ('input_min_area', models.IntegerField(blank=True, default=None, null=True, verbose_name='Minimum Planning Unit Area in sq. meters')),
                ('input_max_area', models.IntegerField(blank=True, default=None, null=True, verbose_name='Maximum Planning Unit Area in sq. meters')),
            ],
            options={
                'abstract': False,
            },
            # bases=('scenarios.scenario',),
        ),
    ]
