# Generated by Django 4.2.30 on 2026-09-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_alter_leaseblockselection_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='objectives',
            field=models.ManyToManyField(blank=True, to='scenarios.objective'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='input_sediment',
            field=models.ManyToManyField(blank=True, to='scenarios.sediment'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='input_substrate',
            field=models.ManyToManyField(blank=True, to='scenarios.substrate'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='input_wea',
            field=models.ManyToManyField(blank=True, to='scenarios.wea'),
        ),
    ]
