# Generated by Django 2.2.10 on 2020-02-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0006_auto_20190319_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoscenario',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios_demoscenario_related', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='planningunitselection',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios_planningunitselection_related', to='contenttypes.ContentType'),
        ),
    ]
